### ISSUE TITLE
Bug Report: [WinError 87] Parameter Incorrect Error in export_audio Function on Windows - GPU is not being found or used

### ISSUE THREAD

**Issue by amihos** [DrewThomasson/ebook2audiobook#182]
When attempting to use the export_audio function within the ebook2audiobook script, an error occurs, resulting in the termination of the process. This error seems to be specific to the Windows environment when running the script via Miniconda.

Steps to Reproduce:

Set up the ebook2audiobook environment using Miniconda on a Windows machine.

Run the script to convert an ebook to an audio format.

Observe the error when the export_audio function is invoked.

Expected Behavior:

The script should successfully execute the export_audio function without encountering any errors.

Actual Behavior:

The following error traceback is observed:

Traceback (most recent call last):
  File "C:\Code\ebook2audiobook-main\lib\functions.py", line 824, in export_audio
    subprocess.run(ffmpeg_cmd, env={}, check=True)
  File "C:\Users\hosam\miniconda3\envs\ebook\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\hosam\miniconda3\envs\ebook\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\hosam\miniconda3\envs\ebook\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] The parameter is incorrect
Caught DependencyError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Code\ebook2audiobook-main\lib\functions.py", line 842, in combine_audio_chapters
    if export_audio():
  File "C:\Code\ebook2audiobook-main\lib\functions.py", line 830, in export_audio
    raise DependencyError(e)
lib.functions.DependencyError: [WinError 87] The parameter is incorrect
Caught DependencyError: [WinError 87] The parameter is incorrect
convert_ebook() Exception: [WinError 87] The parameter is incorrect
Environment:

Operating System: Windows 11

Python Version: 3.10

Miniconda Version: conda 23.9.0

ebook2audiobook Version: latest

Additional Information:

Please note that the error occurs during the execution of the subprocess.run function within the export_audio function. The error message [WinError 87] The parameter is incorrect indicates that there might be an issue with the parameters being passed to the subprocess.run function.

**Comment by robinsones001** [comment]
Hello, I ran cmd and it showed this error. How can I solve it
![image](https://github.com/user-attachments/assets/b2be1767-032f-4bcb-97fc-f716566d8940)

**Comment by ROBERT-MCDOWELL** [comment]
it's a known bug, regex missing from the requirements.txt list.
go to the root folder the run conda activate .\python_env
then pip install regex

**Comment by amihos** [comment]
> Hello, I ran cmd and it showed this error. How can I solve it ![image](https://private-user-images.githubusercontent.com/124541477/399940235-b2be1767-032f-4bcb-97fc-f716566d8940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MDY3NDAsIm5iZiI6MTczNTkwNjQ0MCwicGF0aCI6Ii8xMjQ1NDE0NzcvMzk5OTQwMjM1LWIyYmUxNzY3LTAzMmYtNGJjYi05N2ZjLWY3MTY1NjZkODk0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwM1QxMjE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2VhYmVhMTJiY2YxNWM1ZTUwZDY3MzY1YjlkMDZkNzM0ZDY5MTg5NjdiYzYxY2MxZWY0ZDQ3ZjEwNzg0Njk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4GDV4UPO8tjbSxg37f6QjIeZlyttTXy7KLr3Lbrtd2g)

Is this issue related to what I reported?

**Comment by robinsones001** [comment]
> 这是一个已知的错误，requirements.txt列表中缺少正则表达式。转到根文件夹 Run conda activate .\python_env然后 pip install regex

![image](https://github.com/user-attachments/assets/179688b6-4504-493d-bb78-df5135e1e7d2)

**Comment by ROBERT-MCDOWELL** [comment]
@amihos no, I just saw @robinsones001 cross comment with another issue....
@robinsones001 open a new issue as it has nothing to do with the open issue

**Comment by ROBERT-MCDOWELL** [comment]
btw please provide your cmd line. or tell me if it's from gradio GUI.

**Comment by robinsones001** [comment]
> btw please provide your cmd line. or tell me if it's from gradio GUI.

Running ebook2audiobook.cmd resulted in an error stating that Repex was not installed and crashed before reaching the web link for GUI

**Comment by robinsones001** [comment]
> btw please provide your cmd line. or tell me if it's from gradio GUI.

help me thank you

**Comment by amihos** [comment]
@ROBERT-MCDOWELL 
I ran the using python app.py
and yes its from gradio GUI
I am attaching the full log from terminal to this post.
[log.txt](https://github.com/user-attachments/files/18299752/log.txt)

**Comment by ROBERT-MCDOWELL** [comment]
> > btw please provide your cmd line. or tell me if it's from gradio GUI.
> 
> Running ebook2audiobook.cmd resulted in an error stating that Repex was not installed and crashed before reaching the web link for GUI

please open a new issue!

**Comment by ROBERT-MCDOWELL** [comment]
> @ROBERT-MCDOWELL I ran the program using python app.py and yes its from gradio GUI I am attaching the full log from terminal to this post. [log.txt](https://github.com/user-attachments/files/18299752/log.txt)

first of all, if you run directly app.py you will use your own OS or own python env which is your own risks.
if you want to not waste your time and let the script do everything so run always
.\ebook2audiiobook.cmd

**Comment by amihos** [comment]
The reason that I have created my own conda env and run python app.py is that because running via ebook2audiobook.cmd never picks up my nvidia gpu and always run via cpu. 

Please take a look at log file attached. So i followed a solution mentioned in this post:
https://github.com/DrewThomasson/ebook2audiobook/issues/7#issuecomment-2285310725

**Comment by ROBERT-MCDOWELL** [comment]
so the first thing to say when you open an issue is what you just say now to avoid waste of time....
the second thing is you cannot improvise to install a python env without to know what it needs so you need to be expert in it.
if eb2ab does not see your gpu it can be for multiple reason. no cuda install, or not the right cuda compatible with coqui-tts,
etc... we are busy to fix the urgent bugs for now. so please be the most explicit when open an issue. thanks

**Comment by amihos** [comment]
fair enough and sorry for the confusion. I followed your steps and removed everything and ran the program using the .cmd file. 
yet it still uses the cpu. here is the logs.
[log.txt](https://github.com/user-attachments/files/18301802/log.txt)


which version of cuda is supported? here is what i have installed: 12.7


 ebook2audiobook-main  nvidia-smi
Fri Jan  3 16:46:08 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   57C    P8              8W /   65W |     587MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |

**Comment by ROBERT-MCDOWELL** [comment]
> ::error:: Directory 'C:\Users\hosam\miniconda3' is not empty, please choose a different location
remove completely the folder miniconda3 before to run ./ebook2audiobook.cmd

if you try to install/run with ./ebook2audiobook without to remove completely this miniconda3 folder
so the install will continue on your python OS, causing a lot of trouble if the versions of the package are not the same
and it's what happened to you...

**Comment by amihos** [comment]
I deleted the miniconda folder as you suggested and ran .cmd file again but no difference
[log.txt](https://github.com/user-attachments/files/18302301/log.txt)

**Comment by agentxan** [comment]
After ebook2audiobook.cmd sets up and runs from the cpu I got it to run on the gpu by running the following from the ebook2audiobook folder

conda activate .\python_env
python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
conda deactivate

Then rerun ebook2audiobook.cmd

**Comment by ROBERT-MCDOWELL** [comment]
yes there is a difference, no error anymore and gradio launched.
now when you load a model (around 1.7GB) like DavidAtternborough you should wait until it's loaded and start the conversion

**Comment by amihos** [comment]
> yes there is a difference, no error anymore and gradio launched. now when you load a model (around 1.7GB) like DavidAtternborough you should wait until it's loaded and start the conversion

please check the log. I already did and in the log, it says no gpu detected and it picks up cpu:

...
To create a public link, set `share=True` in `launch()`.
GPU is not available on your device!
Available Processor Unit: cpu

**Comment by ROBERT-MCDOWELL** [comment]
the cuda installed seems to be for cpu indeed, I suggest @agentxan comment

**Comment by amihos** [comment]
> After ebook2audiobook.cmd sets up and runs from the cpu I got it to run on the gpu by running the following from the ebook2audiobook folder
> 
> conda activate .\python_env python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 conda deactivate
> 
> Then rerun ebook2audiobook.cmd

This solved the problem . Thank you very mush guys for the help.

**Comment by amihos** [comment]
### Issue Summary
**Problem:**
The ebook2audiobook project was not detecting or utilizing the NVIDIA GPU on Windows, defaulting to CPU processing instead. This was occurring both when running via `ebook2audiobook.cmd` and through a custom Conda environment.

**Root Cause:**
The default installation wasn't including the correct CUDA-enabled version of PyTorch for GPU support.

**Resolution:**
The issue was resolved by:
1. Removing the existing Miniconda folder and project's python_env
2. Running `ebook2audiobook.cmd` for a clean installation
3. Installing the CUDA-enabled PyTorch version using:
```bash
conda activate .\python_env
python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
conda deactivate
```
4. Rerunning `ebook2audiobook.cmd`

**Suggestions for Future Improvement:**
1. Consider adding automatic detection of NVIDIA GPUs during installation
2. Include the CUDA-enabled PyTorch installation in the default setup script for systems with compatible GPUs
3. Add clear documentation about GPU requirements and setup steps
4. Implement a script to automate the PyTorch CUDA installation for GPU users

Issue can be closed as resolved. Thank you @ROBERT-MCDOWELL and @agentxan for the assistance.
