### ISSUE TITLE
Error: GPU is not available on your device.

### ISSUE THREAD

**Issue by Rasta42** [DrewThomasson/ebook2audiobook#246]
Windows 10
Vediocard: nvidia rtx 3060
Driver version: 566.36

Here someone has problem with "global non-CUDA PyTorch installation"
https://forums.developer.nvidia.com/t/cannot-get-pytorch-to-run-with-cuda-windows-11-and-rtx3060-nvidia-driver-551-23/283320/3

I cant find any "torch" folders except in ebook2audiobook

And cmd print:

pip uninstall torch
WARNING: Skipping torch as it is not installed.

**Comment by ROBERT-MCDOWELL** [comment]
it's a well known issue and should be fixed in the next update

**Comment by ROBERT-MCDOWELL** [comment]
for our project, the only way to satisfy each user with its own GPU working for eb2ab using coqui-tts and pytorch, is to compile pytorch from the sources according to the cuda version and GPU model. the other is to find yourself a pytorch package following your computer and cuda requirements, then activate the python_env of eb2ab:
conda activate
pip uninstall torch
pip cache purge
pip install torch-new-version-with-right-cuda
conda deactivate

**Comment by ROBERT-MCDOWELL** [comment]
could you try with the last git?

**Comment by jdesl** [comment]
Hey Robert, I can give an update. Still get the no GPU message.
last GIT

_conda activate
pip uninstall torch
pip cache purge
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
conda deactivate_

_python -c "import torch; print(torch.cuda.is_available())"_
True

_python -c "import torch; print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'No GPU detected')"_
NVIDIA GeForce GTX 1060

Processing eBook file: Chapter2.pdf
**MPS is not available on your device!**
Available Processor Unit: cpu

Processing eBook file: Chapter2.pdf
**GPU is not available on your device!**
Available Processor Unit: cpu

nvcc --version
_nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0_

**Comment by ROBERT-MCDOWELL** [comment]
did you update your repo? git pull. many changes happened since last month.

**Comment by jdesl** [comment]
I'm on latest release. Deleted and redownloaded project.
Seems there is a mismatch between python_env and miniconda3?

```
conda env list

# conda environments:
base                   C:\Users\User\miniconda3
                       D:\ebook2audiobook\ebook2audiobook\python_env
```

\ **miniconda3** \Lib\site-packages\ **torch-2.6.0+cu118.dist-info**
\ **ebook2audiobook** \python_env\Lib\site-packages\ **torch-2.6.0.dist-info**

Changed source added some prints, in the code torch.cuda.is_available() is indeed false.
```
if session['device'] == 'cuda':
                            session['device'] = session['device'] if torch.cuda.is_available() else 'cpu'
                            print('torch.cuda.is_available()')
                            print(session['device'])
                            print(torch.cuda.is_available())
```

Processing eBook file: Chapter2.pdf
torch.cuda.is_available()
cpu
False
GPU is not available on your device!

**Comment by ROBERT-MCDOWELL** [comment]
eb2ab uses its own virtual python env (the folder .\python_env)  and all extra packages must be installed in this python env, not the python OS at all. so:
conda activate .\python_en
pip install torch-2.6.0+cu118
conda deactivate
ebook2audioboo.cmd [--options]

**Comment by jdesl** [comment]
Awesome, it's working!

Thank you, great project!

**Comment by ROBERT-MCDOWELL** [comment]
glad to know it works for you!

**Comment by nl255** [comment]
I am having the same problem on Windows 10 even after following the CUDA for Windows instructions in Discussions and regardless of which torch I install.

I have runthe following inside the virtual environment (run conda activate in the ebook2audiobook directory)

`python gpu_test.py
Checking PyTorch GPU support...
CUDA is available. Number of GPUs: 1
GPU 0: NVIDIA GeForce RTX 4060 Ti
Running a small test on NVIDIA GeForce RTX 4060 Ti...
GPU computation successful!`

`
>>> import torch
>>> print(torch.cuda.device_count())
1
>>> print(torch.rand(2, 3).cuda())
tensor([[0.5645, 0.5711, 0.2996],
        [0.6965, 0.0163, 0.5840]], device='cuda:0')
>>> print(torch.cuda.is_available())
True
>>> print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'No GPU detected')
NVIDIA GeForce RTX 4060 Ti
`

**Comment by ROBERT-MCDOWELL** [comment]
run into python_env and use to test_gpu.py in tools folder

> regardless of which torch I install

it needs the exact torch compiled with the right python, cuda versions, so there is only one possible

**Comment by ROBERT-MCDOWELL** [comment]
also check https://github.com/DrewThomasson/ebook2audiobook/discussions/477

**Comment by nl255** [comment]
> run into python_env and use to test_gpu.py in tools folder
> 
> > regardless of which torch I install
> 
> it needs the exact torch compiled with the right python, cuda versions, so there is only one possible
> 
> also which version of ebook2audiobook are you using? docker? native? unraid?

Native, and the instructions in #477 are what I used.  As stated above both:
```
conda activate
python
print(torch.rand(2, 3).cuda())
```
works just fine as well as the provided gpu test in the tools directory so doesn't that mean cuda is working properly?

**Comment by Bben-dot** [comment]
> eb2ab uses its own virtual python env (the folder .\python_env) and all extra packages must be installed in this python env, not the python OS at all. so: conda activate .\python_env pip install torch-2.6.0+cu118 conda deactivate ebook2audioboo.cmd [--options]

ran into sam problem, followed this solution, and it worked perfectly.

**Comment by ROBERT-MCDOWELL** [comment]
### from a user for nivida 5000 series:
Set base image: ARG BASE=python:3.12
For the cuda128 build arg (ARG TORCH_VERSION=cuda128), forced PyTorch nightly install:
pip install --no-cache-dir --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
In docker-compose.yml:

Built the image locally:
build:
  context: .
  args:
    TORCH_VERSION: cuda128
Ensured GPU was enabled: deploy: { resources: { reservations: { "<<: *gpu-enabled" } } }

**Comment by DrewThomasson** [comment]
I created a Wiki on this if it helps anyone 

https://github.com/DrewThomasson/ebook2audiobook/wiki/GPU-ISSUES

**Comment by JaCh0o** [comment]
Hello,
Thanks for all explanationbut still cant get with mine... got rtx 5090 with cuda 13.0
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.88                 Driver Version: 580.88         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5090      WDDM  |   00000000:01:00.0  On |                  N/A |
| 30%   39C    P0             43W /  600W |    2549MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

cant find proper repository for cu130 any option for me ?

EDIT:: it is working on 12.8 i guess properlly. 
is there any way to enlarge vram and ram if needed ? ie to 20gb vram and 20 ram ? (to speedup a little bit) ?

**Comment by ROBERT-MCDOWELL** [comment]
torch which is used by coqui-tts  and all other TTS does not support yet cuda13 but max cuda12.8 and partially cuda12.9.  VRAM AND RAM are automatically managed by the TTS engines and torch.

**Comment by JaCh0o** [comment]
> torch which is used by coqui-tts and all other TTS does not support yet cuda13 but max cuda12.8 and partially cuda12.9. VRAM AND RAM are automatically managed by the TTS engines and torch.

therfore is there any option to boost up using rtx5090 32gbvram, 64ram and i9-13900k to do it faster while not losing quality ?
and as of xtts / coqui-tts and others what whould be best performing result with that hardware?
(sorry for ot since its about gpu incomatiblity)

**Comment by ROBERT-MCDOWELL** [comment]
>  to do it faster while not losing quality ?

quality depends exclusively of which TTS engine you choose and its model (xttsv2, bark, vits etc...) and has nothing to do with the GPU and VRAM calculation it needs to convert a text in speech. so if you use xttsv2 on a X GPU card it will take Y time. and on another hardware it will take Z time. 
now the real point should be eb2ab to recognize correctly your GPU first, which involves the right torch package.
and for that, Drew made a wiki and this with the users comment you will find out how to make it correclty.
https://github.com/DrewThomasson/ebook2audiobook/wiki/GPU-ISSUES
then, the performance of your card will depend only by itself.
