### ISSUE TITLE
RTX 5090 (sm_120) GPU Support - CUDA Incompatibility

### ISSUE THREAD

**Issue by bigZos** [DrewThomasson/ebook2audiobook#761]
I'm encountering compatibility issues when trying to enable GPU acceleration. (CPU mode works fine)

GPU: RTX 5090
OS: Windows 11 (using Docker Desktop with WSL2 backend)
Docker Setup: Running via docker-compose using the standard docker-compose.yml provided with the project.

When I configure docker-compose.yml to use the GPU (with <<: *gpu-enabled), the application starts and seems to detect CUDA, but then fails during the TTS model loading/inference phase with errors indicating a PyTorch and CUDA incompatibility with my GPU's architecture (compute capability sm_120).

**Key Error Messages:**

/app/lib/classes/tts_engines/coqui.py:84: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.

  xtts_builtin_speakers_list = torch.load(speakers_path)

Loading TTS xtts model, it takes a while, please be patient...

/usr/local/lib/python3.12/site-packages/torch/cuda/__init__.py:287: UserWarning: 

NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.

The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.

If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/⁠
...
RuntimeError: CUDA error: no kernel image is available for execution on the device

Docker image tags that I've tried: lite, cuda12, latest 

any guidance guidance would be great. happy to provide more detailed logs or information if needed.

**Comment by DrewThomasson** [comment]
Pretty sure the 5090 requires coda 12.8

What happens when you try running the docker tag `cuda128`

**Comment by bigZos** [comment]
yes. youre exaclty right. im running cude version 12.8 

sorry forgot to mention, I did try docker tag cuda128 already. i get the very same error

**Comment by ROBERT-MCDOWELL** [comment]
try to install a pytorch adapted to your GPU
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

useful link:
https://forums.developer.nvidia.com/t/software-migration-guide-for-nvidia-blackwell-rtx-gpus-a-guide-to-cuda-12-8-pytorch-tensorrt-and-llama-cpp/321330?utm_source=chatgpt.com

**Comment by DrewThomasson** [comment]
Yeah it seems the prebuilt builds don’t work

@bigZos 

So you can confirm that by just building the cuda 128 image locally it works then?

**Comment by ROBERT-MCDOWELL** [comment]
sorry I mixed with another discussion...

**Comment by DrewThomasson** [comment]
> [@bigZos](https://github.com/bigZos)
> 
> When you say you got it working did you have to modify anything in the `Dockerfile`?
> 
> Or were you able to use the existing `TORCH_VERSION=cuda128` argument?
> 
> Asking as in the Dockerfile it has
> 
>             "cuda128") \
>                 pip install --no-cache-dir $TORCH_SPEC $TORCHVISION_SPEC $TORCHAUDIO_SPEC --extra-index-url https://download.pytorch.org/whl/nightly/cu128 \
>                 ;; \
> which is slightly different from your
> 
> pip install --no-cache-dir --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> Or is this only a modification to the `docker-compose` file?

@bigZos 
Do these changes look correct to you then for solving this issue?

**Comment by bigZos** [comment]
Yes, building the image locally with the `TORCH_VERSION=cuda128` build argument was the right direction. What made it work was a specific modification I made inside the Dockerfile.

Here’s the modification that solved it for me:

*  I modified the `cuda128)` block in my Dockerfile to be:
    ```dockerfile
    cuda128) \
        echo "Installing PyTorch nightly for CUDA 12.8 (cu128)" && \
        pip install --no-cache-dir --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 \
        ;;
    ```
    It seems using the `--pre` flag and explicitly listing `torch torchvision torchaudio` here (instead of using the `$TORCH_SPEC`, `$TORCHVISION_SPEC`, `$TORCHAUDIO_SPEC` variables, which might be influenced by older versions in `requirements.txt`) was needed to force the installation of the very latest PyTorch nightly versions required.

Regarding PR #766:

Yup the changes you made to the docker-compose.yml look perfect. You just need to include the Dockerfile modification to the PR and it'll get it to work.

**Comment by DrewThomasson** [comment]
Merged into main :-> https://github.com/DrewThomasson/ebook2audiobook/pull/768
